# * 1 ca (not in use now)
# * 1 orderer
# * 2 peers in 1 orgs
# * cli for testing
version: '2.0'

services:
  ca.org1.example.com:
    extends:
      file: docker-compose-base.yaml
      service: ca.org1.example.com

  orderer.example.com:  # There can be multiple orderers
    extends:
      file: docker-compose-base.yaml
      service: orderer.example.com

  peer0.org1.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer0.org1.example.com

  peer1.org1.example.com:
    extends:
      file: docker-compose-base.yaml
      service: peer1.org1.example.com
  
  # cli:
  #   extends:
  #     file: docker-compose-base.yaml
  #     service: cli